### ISSUE TITLE
VideoContainer.tsx 28번째줄 에러

### ISSUE THREAD

**Issue by hwisaac** [React-Team-Project/Youtube-Clone#16]
![image](https://user-images.githubusercontent.com/54179672/212940676-822947f5-064e-4539-a01a-8d71b2603860.png)

- VideoContainer.tsx  28번째줄에서 데이터르 못읽어서 에러

```jsx
let videos = JSON.parse(localStorage.getItem('response')).data.items;
```

> 일단 28번째 줄, 32~37번째 줄 주석 처리하면 에러 없이 작동합니다.

**Comment by hayden365** [comment]
목업데이터로 불러오는 것으로 변경
