### ISSUE TITLE
App.tsx 라우트 중복문제

### ISSUE THREAD

**Issue by hwisaac** [React-Team-Project/Youtube-Clone#17]
## 문제
src/router.tsx 파일내 에서 이미 라우트를 구현하고 있고, index.tsx 에서는 라우트 진입과 프로바이더 컴포넌트를 설정 App.tsx 파일에서는 홈페이지에 전체적인 레이아웃을 설정하였습니다.
그런데`App.tsx` 파일에서 `Routes` 로 중복 라우팅이 적용되어있습니다.

### 해당코드
<img width="444" alt="image" src="https://user-images.githubusercontent.com/54179672/213017193-152c8d1c-3c6d-4039-a572-7b95ae968314.png">

### 기존 라우팅
<img width="445" alt="image" src="https://user-images.githubusercontent.com/54179672/213018393-6c2ef5d8-8805-4eb6-950c-2298583c5a0e.png">

> 디테일 페이지 ( Detail 컴포넌트가 실행됐으나 실제로 컴포넌트는 랜더링 되지 않음 )
![image](https://user-images.githubusercontent.com/54179672/213017366-47b0d463-da63-4d86-83ce-2e6c0e47d37b.png)

### 해결
App.tsx 에 적용된 중복 라우트를 원복

```tsx
// 이전
	const Layout = () => {
		return (
			<>
				<Reset />
				<Header menuClicked={handleMenuClicked} />
				<SNB show={toggle} setShow={setToggle} />
				<Home />
				<Outlet />
				<ReactQueryDevtools initialIsOpen={false} />
			</>
		);
	};

	return (
		<Routes>
			<Route path="*" element={<Layout />}>
				<Route path="home" element={<Home />} />
			</Route>
		</Routes>
	);
```

```tsx
// 수정
	return (
		<>
			<Reset />
			<Header menuClicked={handleMenuClicked} />
			<SNB show={toggle} setShow={setToggle} />
			<Home />
			<Outlet />
			<ReactQueryDevtools initialIsOpen={false} />
		</>
	);
```

**Comment by hayden365** [comment]
아 router.tsx 확인했었는데 무의식적으로 Router만들어버렸네요...
