### ISSUE TITLE
수정 요청

### ISSUE THREAD

**Issue by hwisaac** [React-Team-Project/Youtube-Clone#21]
1. 리액트에서 `a 태그`는 사용하지 말아주세요. 리액트는 SPA 라서 `a` 태그를 사용하면 페이지 전체를 새로고침 하기 때문에 그 잇점을 살릴 수가 없습니다. `Link` 를 사용하면 일부분만 랜더링 합니다.  그리고 `a` 태그는 단독으로 사용하지 말고 `src` 속성으로 어디로 링크시킬지 명시해야 합니다.
> 콘솔에러
![image](https://user-images.githubusercontent.com/54179672/213120310-e8921481-e2d6-42a5-8056-db99b9995c4b.png)

```tsx
// VideoContainer/VideoInfo.tsx
<a>
    <div className="channelName">{video.snippet.channelTitle}</div>
</a>
```
> 수정 제안
```tsx
import { Link } from 'react-router-dom';

<Link to=''>
    <div className="channelName">{video.snippet.channelTitle}</div>
</Link>
```

2. `map` 매서드 사용하여 컴포넌트 요소를 랜더링할 경우 컴포넌트에 **유일한** `key` 값을 할당해야 합니다. (단순 **index 를 key 로 사용하는것은 금지!**) 

- 리액트는 key 값을 가지고 컴포넌트가 동일한지 여부를 판단합니다. 서로 다른 컴포넌트가 동일한 key 값을 가지게 되는 경우 랜더링에서 충돌이 일어날 수 있습니다.

> 에러메세지 
![image](https://user-images.githubusercontent.com/54179672/213121222-53bff12f-fe8f-4ac9-a8bf-00dc6ef0b815.png)

> [Airbnb 스타일가이드](https://github.com/React-Team-Project/Youtube-Clone/wiki/Airbnb-%EB%A6%AC%EC%95%A1%ED%8A%B8(jsx)-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C#props)
![image](https://user-images.githubusercontent.com/54179672/213121100-4d8fc017-67bd-4a98-b03e-3a3a3a46854c.png)

> 문제 코드
```tsx
// VideoContainer.tsx

return (
		<Container>
			{videos.map((video) => (
				<Box>
					<VideoThumbnail video={video} />
					<VideoInfo video={video} />
				</Box>
			))}
		</Container>
	);
```

> (임시) 수정 제안
```tsx
// 만약 VideoContainer 가 여러개 랜더링 될 경우 아래와 같은 키값도 중복되므로 좀더 복잡한 id 값으로 방어해야함

return (
		<Container>
			{videos.map((video,index) => (
				<Box key={`video-${index}`}>
					<VideoThumbnail video={video} />
					<VideoInfo video={video} />
				</Box>
			))}
		</Container>
	);
};
```

4. SNB 컴포넌트 랜더링 충돌 현상
> 에러메세지
![image](https://user-images.githubusercontent.com/54179672/213122284-d8ca22aa-ae2e-407c-9e69-af167c870e7b.png)

> 코드
![image](https://user-images.githubusercontent.com/54179672/213122475-5c25b88a-ac56-40ce-8f3b-2354167f0765.png)

- 원인추측.`SNB` 컴포넌트는 `App.tsx` 에서 랜더링 하고 있습니다. 그리고 `toggle` state 를 조절하며 마운트 여부를 조절하려는 코드인 것으로 보입니다.
- 이 로직이 충돌을 일으킵니다. (이미 상위컴포넌트인 `App.tsx` 에서 **존재 했는데**,  `SNB.tsx` 의 로직에서는 다시 `show` 에 따라 **존재할수도 존재하지 않을 수도** 있는 코드를 작성한 것이 원인으로 추측)

> 수정방향
![image](https://user-images.githubusercontent.com/54179672/213122874-8104dc98-67c2-448a-a5aa-6db6982cffb4.png)

- `&&` 단축평가를 사용해서 `toggle` 이 `true` 일 때 App.tsx 파일에서 랜더링 하도록 수정하면 충돌이 일어나지 않습니다.

**Comment by hyojina** [comment]
4번 확인중입니다..!

**Comment by hyojina** [comment]
4번 요청 확인했는데, 
제가 코드 수정 전인데 제 컴퓨터에서는 에러가 안뜨네요.
아마 다른 쪽에서 수정된 것 같습니다(아마도 승윤님!)

**Comment by hwisaac** [comment]
```tsx
const isMain = window.location.pathname === '/' || window.location.pathname === '/search' ? true : false;
	if (pathname !== window.location.pathname) {
		pathname = window.location.pathname;
		setShow(false);
	}
	if (!firstRender) {
		setShow(true);
		firstRender = !firstRender;
	}

```
이 코드가 `/` 랑 `/search` 두 군데서만 작동 하고 있어서 `/:id` 의 디테일 페이지에서 `SNB` 를 열때 충돌 일어납니다.

https://user-images.githubusercontent.com/54179672/213154874-d255a018-8254-4070-92cc-866f972b27f7.mp4

**Comment by hyojina** [comment]
확인해보겠습니다!

**Comment by hyojina** [comment]
일단 이삭님이 알려주신대로 수정 해보았는데, 사이드바가 아예 나오질 않는...것 같아요 (제가 뭘 잘못한걸지두ㅠㅠ)

SNB는 승윤님이 작성하신 코드로, 제가 첨 show를 추가한 건 메뉴 아이콘 클릭 시 
사이드바가 보이도록 display를 컨트롤하려고 추가한거였어요!
지금은 SNB에 반응형도 추가되면서 처음과 다르게 코드가 쪼~끔 많아져서,
낼 회의때 승윤님이랑 같이 얘기해보면 좋을 것 같아요!!

+) 마지막으로 코멘트 달아주신 저 부분 수정하면 될 .. 것 같네욤..!!

**Comment by hayden365** [comment]
key값에 Math.random()으로 난수를 따로 생성해야하는지 아니면 videoId데이터만으로 충분할지 궁금하네요

**Comment by syoon0624** [comment]
@hwisaac @Hyojina 이제서야 확인했네요! ㅠㅠ
일단 단축평가로 SNB 컴포넌트의 렌더링을 관리하게 된다면, 초기 toggle값이 false이기 때문에, 사이드바는 안나오게 됩니다! 따라서
toggle 초기화값을 true로 수정한 후, 이에 맞추어 작업 할 수 있도록 하겠습니다~

**Comment by syoon0624** [comment]
toogle 여부에 따라 화면이 반응하여 렌더링되기 때문에, 단축평가를 적용하기엔 무리가 있어 보여 단축평가를 제외했습니다!
