### ISSUE TITLE
(2차) 전반적으로 코드 수정완료

### ISSUE THREAD

**Issue by hwisaac** [React-Team-Project/Youtube-Clone#42]
- 이 코드는 refactor 브랜치에 업로드만 했습니다.

### Home.tsx 
1. useState, useEffect , searchData 비동기 함수 코드를 useQuery 훅으로 대체
```tsx
// 변경전
	const [videos, setVideos] = useState([]);

	useEffect(() => {
		searchData();
	}, []);

	const searchData = async () => {
		let result = await youtube.search('beautiful');
		const items = result.items;
		setVideos(items);
	};
// 변경후
	const {isLoading, data: result} = useQuery<ISearch>(['search',"beautiful"], ()=> youtube.search('beautiful'))
```
2. `videos` 대신 `result.items`, isLoading 과 함께 단축평가로 VideoLink 랜더링 
```tsx
// 변경전
{videos.map((video, index) => (
	<div className="video-element" key={`${index}${video.id.videoId}`}>
		<VideoLink to={'/' + video.id.videoId} key={video.id.videoId} className="video-element">
			{video ? <VideoContainer video={video} /> : null}
		</VideoLink>
	</div>
))}
// 변경후
{!isLoading && result.items.map((video, index) => (
	<div className="video-element" key={`${index}${video.id.videoId}`}>
		<VideoLink to={'/' + video.id.videoId} key={video.id.videoId} className="video-element">
			{video ? <VideoContainer video={video} /> : null}
		</VideoLink>
	</div>
))}

```  
3. 아무 효과 없는 video-container 클래명과 div 에 달린 video-element 클래스명도 삭제
4. VideoLink 에 달린 video-element 클래스명 삭제하고 해당 스타일을 VideoLink 로 인라인

> 좌: 변경전, 우: 변경후

![image](https://user-images.githubusercontent.com/54179672/213689885-6c9136e3-8347-4e59-96f7-44d8bcd5ef2c.png)

5. `'/' + video.id.videoId` 를 템플릿리터럴로 변경 `/${video.id.videoId}`
6. undefined 인 경우의 에러처리를 useQuery 의 isLoading 으로 처리하므로 삼항연산자로 VideoContainer 랜더유무 코드 수정 
```tsx
// 수정전
{video ? <VideoContainer video={video} /> : null}
// 수정후
<VideoContainer video={video} />
```

## VideoContainer
> 상위 컴포넌트에서 fetching 하고 데이터를 갈무리하여 children 으로 그 정보를 보내서 랜더링 하게 수정

1. 채널 데이터 가져오는 비동기 코드를 `useQuery` 로 대체 
2. 단축평가에서 `channelInfo` 제거. 해당 객체값에 유효값이 딱히 채워지지 않아도 언제나 `truethy` 이므로 의미가 없음 
3. videoInfo  컴포넌트 에 channelInf 프롭을 전달하지 않게 수정(해당 컴포넌트에서 이 state를 사용하지 않음)
4. Channel 컴포넌트에서 channel-element 클래스명 제거 (해당 클래스명의 스타일을 사용하지 않음)
5. VideoContainer 컴포넌트에서 video 데이터를 VideoThumbnail 과 VideoInfo 에 넘긴후 각각 데이터를 패칭 하고 있기 떄문에 VideoContainer 에서 한꺼번에 패칭하고 그 결과를 VideoThumbnail 과 VideoInfo 로 넘기는 방향으로 수정
6. VideoContainer 는 kind 가 video 일 경우 Video 관련 컴포넌트를 랜더링하고 Channel 에 관련된 경우 Channel 관련 컴포넌트를 랜더링 하는데 각각 맞는 `videoBrief` 와 `channelBrief` state를 넘기도록 수정함
7. channelBrief 와 videoBrief 에 관한 타입 세팅

```tsx
// 수정전
if (video.id.kind === 'youtube#video') {
	return (
		<>
			{video && channelInfo && (
				<>
					<VideoThumbnail video={video} />
					<VideoInfo video={video} channelInfo={channelInfo} />
				</>
			)}
		</>
	);
} else if (video.id.kind === 'youtube#channel') {
	return (
		<Channel className="channel-element">
			{channelInfo ? <ChannelContainer video={video} channelInfo={channelInfo} /> : null}
		</Channel>
	);
}
// 수정후
if (video.id.kind === 'youtube#video') {
	return (
		<>
			{videoBrief.isLoading && <VideoThumbnail videoBrief={videoBrief} />}
			{videoBrief.isLoading && <VideoInfo videoBrief={videoBrief} />}
		</>
	);
} else if (video.id.kind === 'youtube#channel') {
	return <Channel>{channelBrief.isLoading && <ChannelContainer channelBrief={channelBrief} />}</Channel>;
}
```

### VideoInfo.tsx 
1. 데이터 패칭 코드 삭제
2. VideoConatiner 변경에 맞춰서 수정함

### VideoThumbnail.tsx
1. 데이터 패칭 코드 삭제
2. VideoConatiner 변경에 맞춰서 수정함

### ChannelContainer.tsx
1. VideoConatiner 변경에 맞춰서 수정함
2. 디자인 약간 수정

## Recommend
1. 캐시 데이터 사용하지 않는 문제 수정

**Comment by hayden365** [comment]
videoContainer에서 필요한 데이터를 한번에 불러와서 굉장히 깔끔해졌네요 useOutletContext로 toggleSNB불러와서 boolean값에 따라 메인화면 left px을 조정하는 부분만 따로 추가했습니다.
리팩토링 감사합니다~
